# Generated by Django 4.2.20 on 2025-04-23 06:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_document', models.FileField(blank=True, null=True, upload_to='documents/appointment_document/')),
                ('offer_letter', models.FileField(blank=True, null=True, upload_to='documents/offer_letter/')),
                ('company_policies', models.FileField(blank=True, null=True, upload_to='documents/company_policies')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='employees',
            name='emp_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photo/'),
        ),
        migrations.AddField(
            model_name='employees',
            name='marital_status',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='employees',
            name='reporting_mng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.documentaccess'),
        ),
    ]
