# Generated by Django 4.2.20 on 2025-04-23 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0002_documentaccess_employees_emp_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('Resignation', 'Resignation'), ('Termination', 'Termination'), ('Absconding', 'Absconding')], max_length=50)),
                ('clearance_form', models.FileField(blank=True, null=True, upload_to='clearance_forms/')),
                ('experience_letter', models.FileField(blank=True, null=True, upload_to='experience_letters/')),
                ('relieving_letter', models.FileField(blank=True, null=True, upload_to='relieving_letters/')),
                ('asset_handover', models.BooleanField(default=False)),
                ('no_dues_submission', models.BooleanField(default=False)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees')),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('issue_date', models.DateField()),
                ('asset_code', models.CharField(max_length=50)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee_information.employees')),
            ],
        ),
    ]
