# Generated by Django 4.2.20 on 2025-04-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0003_exitdetails_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='education_qualification',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='employees',
            name='emergency_contact_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='emergency_contact_number',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='last_emp_details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
