# Generated by Django 4.2.20 on 2025-04-24 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0004_employees_education_qualification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitdetails',
            name='clearance_chk',
            field=models.BooleanField(default=False),
        ),
    ]
