# Generated by Django 4.2.20 on 2025-04-25 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0005_exitdetails_clearance_chk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees'),
        ),
    ]
