# Generated by Django 4.2.20 on 2025-04-28 05:47
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0006_alter_asset_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
        migrations.RemoveField(
            model_name='department',
            name='status',
        ),
        migrations.RemoveField(
            model_name='position',
            name='description',
        ),
        migrations.RemoveField(
            model_name='position',
            name='status',
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.TextField(blank=True, null=True),
        ),
    ]
