# Generated by Django 4.2.20 on 2025-04-29 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee_information', '0007_remove_department_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='code',
            new_name='emp_code',
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
