# Generated by Django 4.2.20 on 2025-04-29 03:49

from django.db import migrations
from django.contrib.auth.models import Group



def create_employee_group(apps,schema_editor):
    Group.objects.get_or_create(name="Employee")



class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0008_rename_code_employees_emp_code_employees_user'),
    ]

    operations = [
        migrations.RunPython(create_employee_group),
    ]
