# Generated by Django 4.2.20 on 2025-05-01 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0009_auto_20250429_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='exitdetails',
            name='no_dues_form',
            field=models.FileField(blank=True, null=True, upload_to='no_dues_form/'),
        ),
    ]
