# Generated by Django 4.2.20 on 2025-05-01 07:57

from django.db import migrations, models
import django.db.models.deletion
import django_jsonfield_backport.models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0010_exitdetails_no_dues_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_entitlement', models.PositiveIntegerField(default=20)),
                ('leaves_availed', django_jsonfield_backport.models.JSONField(default=dict)),
                ('leave_balance', models.PositiveIntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee_information.employees')),
            ],
        ),
    ]
