# Generated by Django 4.2.20 on 2025-05-02 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0011_employeeleave'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
