# Generated by Django 4.2.20 on 2025-05-02 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0012_holiday'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holiday',
            old_name='name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='holiday',
            name='date',
        ),
        migrations.AddField(
            model_name='holiday',
            name='holiday_file',
            field=models.FileField(blank=True, null=True, upload_to='documents/holiday_file/'),
        ),
    ]
