# Generated by Django 4.2.20 on 2025-05-02 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_information', '0013_rename_name_holiday_title_remove_holiday_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='holiday',
            name='title',
        ),
    ]
